POST https://localhost:3000/Themba/Report HTTP/1.1
content-type: application/json

{
    "ID": "Solid1",
    "Name": "Renton",
    "Surname": "Foss",
    "DayAndTime": "2023-05-09 15:00",
    "Description": "Testing Statement 1"

}
###
POST https://localhost:3000/Themba/Register HTTP/1.1
content-type: application/json

{
    "Username": "Jake",
    "Passcode": "L@mbert_7835$#"
}
###
POST https://localhost:3000/Themba/Login HTTP/1.1
content-type: application/json

{
    "Username": "Jake",
    "Passcode": "L@mbert_7835$#"
}
###
GET https://localhost:3000/Themba/Dashboard HTTP/1.1
content-type: application/json
Authorization: Bearer

{

}
###
PATCH https://localhost:3000/Themba/UpdateAppointments HTTP/1.1
content-type: application/json
Authorization: Bearer

{

}