POST https://localhost:3000/Themba/Report HTTP/1.1
content-type: application/json

{
    "ID": "Solid8",
    "Name": "Renton",
    "Surname": "Foss",
    "DayAndTime": "15 March 2023",
    "Description": "Testing Statement 1"

}
###
POST https://localhost:3000/Themba/Register HTTP/1.1
content-type: application/json

{
    "Username": "SnakeEater97",
    "Passcode": "L@mbert_7835$#"
}
###
POST https://localhost:3000/Themba/Login HTTP/1.1
content-type: application/json

{
    "Username": "SnakeEater97",
    "Passcode": "L@mbert_7835$#"
}
###
GET https://localhost:3000/Themba/Dashboard HTTP/1.1
content-type: application/json
Authorization: Bearer

{

}
###
PATCH https://localhost:3000/Themba/UpdateAppointments HTTP/1.1
content-type: application/json
Authorization: Bearer

{
    "ID": "Solid8",
    "Name": "Renton",
    "Surname": "Foss",
    "DayAndTime": "15 March 2023",
    "Description": "Testing Statement 1"
}
###
POST https://localhost:3000/Themba/ValidateSession HTTP/1.1
content-type: application/json 

{
    "ID":"Revolver Ocelot",
    "Name":"ACDP",
    "Surname":"Foss96",
    "DayAndTime": "2023-05-09 15:00"

}
