//Report Related Functions - Reserved For Patients
###
POST https://localhost:3000/Themba/Report HTTP/1.1
content-type: application/json

{
    "ID": "Solid11",
    "Name": "Renton",
    "Surname": "Foss",
    "DayAndTime": "19 March 2023 19:00",
    "Description": "Testing Statement 1"

}
//User Related Functions - Reserved For Counselors
###
POST https://localhost:3000/Themba/Register HTTP/1.1
content-type: application/json

{
    "Username": "Thamsanqa Veli",
    "Passcode": "Benni(4205^#"
}
###
POST https://localhost:3000/Themba/Login HTTP/1.1
content-type: application/json

{
    "Username": "Thamsanqa Veli",
    "Passcode": "Benni(4205^#"
}
//Appointment Related Functions - Reserved For Counselors
###
GET https://localhost:3000/Themba/Dashboard HTTP/1.1
content-type: application/json

{

}
###
PATCH https://localhost:3000/Themba/UpdateAppointments HTTP/1.1
content-type: application/json

{
    "ID": "PT-51178813",
    "Name": "Michael",
    "Surname": "Von Pierre",
    "DayAndTime": "18 March 2023 15:00"
}
//Appointment Related Functions - Reserved For Counselors & Patients
###
POST https://localhost:3000/Themba/ValidateSession HTTP/1.1
content-type: application/json 

{
    "ID":"PT-51178812",
    "Name":"Michael",
    "Surname":"Von Pierre",
    "DayAndTime": "18 March 2023 15:00"

}
###
GET https://localhost:3000 HTTP/1.1